# Welcome to Jekyll!
#

# Site settings
title: Nayantara Parpia Kathak Dancer
description: 
owner: Nayantara Parpia # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: nayantara.parpia@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nayantaraparpia.com" # the base hostname & protocol for your site
social:
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/nayantaraparpia
  email: mailto:nayantara.parpia@gmail.com
  #flickr:
  instagram: https://www.instagram.com/nayantara_kathak/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
prose:
  rooturl: '_posts'
  siteurl: 'http://nayantaraparpia.github.io/'
  relativeLinks: 'http://nayantaraparpia.github.io/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
